version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
        test:
          - "CMD"
          - "rabbitmqctl"
          - "status"
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      - test

  mongo:
    image: "mongo:latest"
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - test
  
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8080:8081"
    restart: on-failure
    networks:
      - test

  seleniumhub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - test

  firefoxnode:
    image: selenium/node-firefox-debug
    ports:
      - 5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - test

networks:
  test:
    driver: bridge
volumes:
  mongodata: