version: '3.3'

services:
  screenshot-api:
    build:
      context: ./
      dockerfile: ./src/Screenshot.API/Dockerfile
    environment:
      - RabbitMqConnection__HostName=rabbitmq
      - RabbitMqConnection__Password=guest
      - RabbitMqConnection__Username=guest
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=Screenshots_dkr
    ports:
      - "5000:80"
    restart: on-failure
    volumes:
      - "./scripts/wait-for-it.sh:/app/wait-for-it.sh"
    entrypoint: ["bash", "-c" ,"./wait-for-it.sh rabbitmq:15672 -t 0; dotnet Screenshot.API.dll"]
    networks:
      - test
  screenshot-processor:
    build:
      context: ./
      dockerfile: ./src/Screenshot.Processor/Dockerfile
    environment:
      - RabbitMqConnection__HostName=rabbitmq
      - RabbitMqConnection__Password=guest
      - RabbitMqConnection__Username=guest
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=Screenshots_dkr
      - WebDriverType=Remote
    restart: on-failure
    volumes:
      - "./scripts/wait-for-it.sh:/app/wait-for-it.sh"
    entrypoint: ["bash", "-c" ,"./wait-for-it.sh rabbitmq:15672 -t 0; dotnet Screenshot.Processor.dll"]
    networks:
      - test

networks:
  test:
    driver: bridge